<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="9" total="10" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-18T16:45:39 CST" name="Default suite" finished-at="2022-03-18T16:46:10 CST" duration-ms="30476">
    <groups>
      <group name="Cart">
        <method signature="Exercise4.tc_REQ009_001()[pri:0, instance:exercise4.Exercise4@1b2abca6]" name="tc_REQ009_001" class="exercise4.Exercise4"/>
      </group> <!-- Cart -->
    </groups>
    <test started-at="2022-03-18T16:45:39 CST" name="Default test" finished-at="2022-03-18T16:46:10 CST" duration-ms="30476">
      <class name="exercise4.Exercise4">
        <test-method is-config="true" signature="startUp()[pri:0, instance:exercise4.Exercise4@1b2abca6]" started-at="2022-03-18T16:45:39 CST" name="startUp" finished-at="2022-03-18T16:45:48 CST" duration-ms="8568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method signature="tc_REQ009_001()[pri:0, instance:exercise4.Exercise4@1b2abca6]" started-at="2022-03-18T16:45:48 CST" name="tc_REQ009_001" finished-at="2022-03-18T16:46:03 CST" duration-ms="15319" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at exercise4.Exercise4.tc_REQ009_001(Exercise4.java:295)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_REQ009_001 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:exercise4.Exercise4@1b2abca6]" started-at="2022-03-18T16:46:03 CST" name="tearDown" finished-at="2022-03-18T16:46:10 CST" duration-ms="6538" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tc_REQ009_001 status=FAILURE method=Exercise4.tc_REQ009_001()[pri:0, instance:exercise4.Exercise4@1b2abca6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- exercise4.Exercise4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
